version: "3.8"

services:
  db:
    image: mysql:8
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: todo-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/task_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8088
    ports:
      - "8088:8088"

  frontend:
    build: ./frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
# command: ["/wait-for-it.sh", "db", "--", "java", "-jar", "app.jar"]
